version: "3.9"
services:
  main:
    build: .
    network_mode: host
    volumes:
      - /home/${USER}/canserver-logs:/tmp/canserver-logs
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    stop_grace_period: 30s
    depends_on:
      - redis
    command: "python main.py -a 10.42.0.1:5000 -p 10.42.0.1:1338 --timesync"
    restart: always
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
